version: 2
defaults: &defaults
  docker:
    - image: circleci/node:11.10.0-browsers
  working_directory: ~/repo

restore_src_cache: &restore_src_cache
  keys:
    - source-v7-{{ .Branch }}-{{ .Revision }} # cache hit from the current git revision
    - source-v7-{{ .Branch }}- # cache hit from the current branch
    - source-v7- # any cache hit

save_src_cache: &save_src_cache
  key: source-v7-{{ .Branch }}-{{ .Revision }}
  paths:
    - ~/repo

restore_npm_cache: &restore_npm_cache
  keys:
    - npm-deps-v7-{{ checksum "package.json" }}
    # fallback to using the latest cache if no exact match is found
    - npm-deps-v7-

save_npm_cache: &save_npm_cache
  key: npm-deps-v7-{{ checksum "package.json" }}
  paths:
    - node_modules

save_build_cache: &save_build_cache
  key: build-v7-{{ .Branch }}-{{ .Revision }}
  paths:
    - ~/repo/dist

restore_build_cache: &restore_build_cache
  keys:
    - build-v7-{{ .Branch }}-{{ .Revision }}

jobs:
  install:
    <<: *defaults
    steps:
      - restore_cache: *restore_src_cache
      - checkout
      - save_cache: *save_src_cache
      - restore_cache: *restore_npm_cache
      - run: npm install
      - save_cache: *save_npm_cache

  build:
    <<: *defaults
    steps:
      - restore_cache: *restore_src_cache
      - restore_cache: *restore_npm_cache
      - run:
          name: build
          command: bash circleBuild.sh
      - save_cache: *save_build_cache

  test:
    <<: *defaults
    steps:
      - restore_cache: *restore_src_cache
      - restore_cache: *restore_npm_cache
      - run: yarn test

  release:
    <<: *defaults
    steps:
      - restore_cache: *restore_src_cache
      - restore_cache: *restore_npm_cache
      - restore_cache: *restore_build_cache
      - run:
          name: release
          command: yarn release

workflows:
  version: 2
  main:
    jobs:
      - install
      - build:
          requires:
            - install
      - test:
          requires:
            - build
      - release:
          requires:
            - test
